export const CHANGE_REGISTER_INPUT_NAME = "CHANGE_REGISTER_INPUT_NAME";
export const CHANGE_REGISTER_INPUT_EMAIL = "CHANGE_REGISTER_INPUT_EMAIL";
export const CHANGE_REGISTER_INPUT_PASSWORD = "CHANGE_REGISTER_INPUT_PASSWORD";
export const CHANGE_REGISTER_INPUT_PASSWORD2 =
  "CHANGE_REGISTER_INPUT_PASSWORD2";

export const RECEIVE_ERROR = "RECEIVE_ERROR";
