export const CHANGE_INPUT_NAME = "CHANGE_INPUT_NAME";
export const CHANGE_INPUT_EMAIL = "CHANGE_INPUT_EMAIL";
export const CHANGE_INPUT_PASSWORD = "CHANGE_INPUT_PASSWORD";
export const CHANGE_INPUT_PASSWORD2 = "CHANGE_INPUT_PASSWORD2";

export const RECEIVE_ERROR = "RECEIVE_ERROR";
export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
