export const CHANGE_REGISTER_INPUT_NAME = "CHANGE_REGISTER_INPUT_NAME";
export const CHANGE_REGISTER_INPUT_EMAIL = "CHANGE_REGISTER_INPUT_EMAIL";
export const CHANGE_REGISTER_INPUT_PASSWORD = "CHANGE_REGISTER_INPUT_PASSWORD";
export const CHANGE_REGISTER_INPUT_PASSWORD2 =
  "CHANGE_REGISTER_INPUT_PASSWORD2";

export const RECEIVE_REGISTER_ERROR = "RECEIVE_REGISTER_ERROR";
export const CLEAR_ALL_REGISTER_STATES = "CLEAR_ALL_REGISTER_STATES";
