export const CHANGE_EDU_INPUT_SCHOOL = "CHANGE_EDU_INPUT_SCHOOL";
export const CHANGE_EDU_INPUT_DEGREE = "CHANGE_EDU_INPUT_DEGREE";
export const CHANGE_EDU_INPUT_FIELD_OF_STUDY =
  "CHANGE_EDU_INPUT_FIELD_OF_STUDY";
export const CHANGE_EDU_INPUT_FROM = "CHANGE_EDU_INPUT_FROM";
export const CHANGE_EDU_INPUT_TO = "CHANGE_EDU_INPUT_TO";
export const CHANGE_EDU_INPUT_CURRENT = "CHANGE_EDU_INPUT_CURRENT";
export const CHANGE_EDU_INPUT_DESCRIPTION = "CHANGE_EDU_INPUT_DESCRIPTION";

export const RECEIVE_EDU_ERRORS = "RECEIVE_EDU_ERRORS";
