export const CHANGE_EXPERIENCE_INPUT_COMPANY =
  "CHANGE_EXPERIENCE_INPUT_COMPANY";
export const CHANGE_EXPERIENCE_INPUT_TITLE = "CHANGE_EXPERIENCE_INPUT_TITLE";
export const CHANGE_EXPERIENCE_INPUT_LOCATION =
  "CHANGE_EXPERIENCE_INPUT_LOCATION";
export const CHANGE_EXPERIENCE_INPUT_FROM = "CHANGE_EXPERIENCE_INPUT_FROM";
export const CHANGE_EXPERIENCE_INPUT_TO = "CHANGE_EXPERIENCE_INPUT_TO";
export const CHANGE_EXPERIENCE_INPUT_CURRENT =
  "CHANGE_EXPERIENCE_INPUT_CURRENT";
export const CHANGE_EXPERIENCE_INPUT_DESCRIPTION =
  "CHANGE_EXPERIENCE_INPUT_DESCRIPTION";

export const RECEIVE_EXPERIENCE_ERRORS = "RECEIVE_EXPERIENCE_ERRORS";
