export const GET_PROFILE_BY = "GET_PROFILE_BY";
export const GET_CURRENT_USER_PROFILE = "GET_CURRENT_USER_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_ALL_PROFILES = "GET_ALL_PROFILES";
export const RECEIVE_PROFILE_ERRORS = "RECEIVE_PROFILE_ERRORS";
export const CLICK_EDIT_PROFILE = "CLICK_EDIT_PROFILE";

export const CHANGE_PROFILE_HANDLE_INPUT = "CHANGE_PROFILE_HANDLE_INPUT";
export const CHANGE_PROFILE_STATUS_SELECT = "CHANGE_PROFILE_STATUS_SELECT";
export const CHANGE_PROFILE_COMPANY_INPUT = "CHANGE_PROFILE_COMPANY_INPUT";
export const CHANGE_PROFILE_WEBSITE_INPUT = "CHANGE_PROFILE_WEBSITE_INPUT";
export const CHANGE_PROFILE_LOCATION_INPUT = "CHANGE_PROFILE_LOCATION_INPUT";
export const CHANGE_PROFILE_SKILLS_INPUT = "CHANGE_PROFILE_SKILLS_INPUT";
export const CHANGE_PROFILE_GITHUB_INPUT = "CHANGE_PROFILE_GITHUB_INPUT";
export const CHANGE_PROFILE_BIO_INPUT = "CHANGE_PROFILE_BIO_INPUT";
export const CHANGE_PROFILE_TWITTER_INPUT = "CHANGE_PROFILE_TWITTER_INPUT";
export const CHANGE_PROFILE_FACEBOOK_INPUT = "CHANGE_PROFILE_FACEBOOK_INPUT";
export const CHANGE_PROFILE_LINKEDIN_INPUT = "CHANGE_PROFILE_LINKEDIN_INPUT";
export const CHANGE_PROFILE_YOUTUBE_INPUT = "CHANGE_PROFILE_YOUTUBE_INPUT";
export const CHANGE_PROFILE_INSTAGRAM_INPUT = "CHANGE_PROFILE_INSTAGRAM_INPUT";

export const CLEAR_ALL_PROFILE_STATE = "CLEAR_ALL_PROFILE_STATE";
