export const CHANGE_LOGIN_INPUT_EMAIL = "CHANGE_LOGIN_INPUT_EMAIL";
export const CHANGE_LOGIN_INPUT_PASSWORD = "CHANGE_LOGIN_INPUT_PASSWORD";
export const RECEIVE_LOGIN_ERROR = "RECEIVE_LOGIN_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CLEAR_ALL_LOGIN_STATE = "CLEAR_ALL_LOGIN_STATE";
