export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const RECEIVE_COMMENT_ERRORS = "RECEIVE_COMMENT_ERRORS";

export const CHANGE_COMMENT_CONTENT_TO_ADD = "CHANGE_COMMENT_CONTENT_TO_ADD";
export const COMMENT_LOADING = "COMMENT_LOADING";
export const CLEAR_COMMENT_FORM = "CLEAR_COMMENT_FORM";
